### ISSUE TITLE
No files to exctract from unknown.zip

### ISSUE THREAD

**Issue by bellash13** [TimCorey/VSZipper#3]
Could you throw a file not found exception instead of generating an unknown.zip that is corrupted? I would  like to send you a pull request to update your code if you wish to. Please add me as contributor

    `public void Zip()
    {
        string folder = AppDomain.CurrentDomain.BaseDirectory;
        var slnFile = new DirectoryInfo(folder).GetFiles("*.sln");
        if(!slnFile.Any()){
            throw new FileNotFoundException("Solution file was not found inside this directory.");
        }
        string zipFile = $"{slnFile?.FirstOrDefault()?.Name[..^4]}.zip";
        Zip(folder, zipFile);
    }`

**Comment by TimCorey** [comment]
The empty zip file is a different issue than the unknown.zip. It sounds like the application did not complete the process of filling the zip file. I liked the option of unknown.zip when it could not find the sln file because that's not a big deal. You could be zipping up a project file and it would still work. Let's not throw an exception when it isn't necessary.

As for the empty zip file, I would be interested in what situation caused it. That's the issue that needs to be addressed.

As for submitting pull requests, you don't need to be a contributor to submit a pull request. Just fork the repo, make the change, and submit the pull request from there.
